### ISSUE TITLE
install react-navigation

### ISSUE THREAD

**Issue by Ahmed-Imam** [nathvarun/React-Navigation-2.0-Tutorial#2]
I am new to React Native just finished with Expo Setup and my App is running fine on both Android and ios Simulator but After npm install react-navigation which installed for me react navigation 2.14.2 my app crushed with **unhandled JS Exception: Requiring module 'fetch', which threw an exception: ReferenceError: Can't find Varible:self**

**Comment by rajat-np** [comment]
Please refer this [answer], it might help you. 
(https://stackoverflow.com/questions/52269560/react-native-expo-cant-find-variable-self)

**Comment by rajat-np** [comment]
Please refer this [answer](https://stackoverflow.com/questions/52269560/react-native-expo-cant-find-variable-self), it might help you.
