### ISSUE TITLE
Question with real Data -Structuring You App - Combining Navigators

### ISSUE THREAD

**Issue by cruizg** [nathvarun/React-Navigation-2.0-Tutorial#3]
Hello I follow your YouTube videos are well didactic, but I have a question maybe very simple, if I have the logeo with a database (Welcome.js) or firebase, as I passed the information I got (username, icon) from the screen son(welcome.js) to the father (app.js there is the name of the user, icon).
I appreciate it
Thanks

**Comment by nathvarun** [comment]
Hey hope you've figured this out. However i couldn't understand your question. Kindly reopen an issue if required.
